import * as Joi from 'joi';

export const configValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test').default('development'),
  APP_PORT: Joi.number().default(3001),
  DATABASE_URL: Joi.string().required(),
  REDIS_URL: Joi.string().required(),
  MINIO_ENDPOINT: Joi.string().required(),
  MINIO_PORT: Joi.number().default(9000),
  MINIO_USE_SSL: Joi.string().default('false'),
  MINIO_ACCESS_KEY: Joi.string().required(),
  MINIO_SECRET_KEY: Joi.string().required(),
  MINIO_BUCKET: Joi.string().default('cnpv-documents'),
  JWT_SECRET: Joi.string().min(32).required(),
  JWT_REFRESH_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_EXPIRY: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRY: Joi.string().default('7d'),
  MFA_TEMP_TOKEN_EXPIRY: Joi.string().default('5m'),
  ANTHROPIC_API_KEY: Joi.string().required(),
  EMBEDDING_MODEL: Joi.string().default('voyage-3'),
  EMBEDDING_DIMENSION: Joi.number().default(1024),
  LLM_MODEL: Joi.string().default('claude-sonnet-4-6'),
  LLM_MAX_TOKENS: Joi.number().default(2048),
  LLM_TEMPERATURE: Joi.number().default(0.1),
  RAG_CHUNK_SIZE: Joi.number().default(500),
  RAG_CHUNK_OVERLAP: Joi.number().default(50),
  RAG_TOP_K_RETRIEVE: Joi.number().default(20),
  RAG_TOP_K_RERANK: Joi.number().default(5),
  ENCRYPTION_KEY: Joi.string().min(32).required(),
  BCRYPT_ROUNDS: Joi.number().default(12),
  CORS_ORIGIN: Joi.string().default('http://localhost:3000'),
});
