export enum AuditEventType {
  // Auth
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  MFA_ENABLED = 'MFA_ENABLED',
  MFA_VERIFIED = 'MFA_VERIFIED',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  // Users
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  // Documents
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_SUBMITTED_REVIEW = 'DOCUMENT_SUBMITTED_REVIEW',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED',
  DOCUMENT_INDEXED = 'DOCUMENT_INDEXED',
  DOCUMENT_ACTIVATED = 'DOCUMENT_ACTIVATED',
  DOCUMENT_EXPIRED = 'DOCUMENT_EXPIRED',
  DOCUMENT_VIEWED = 'DOCUMENT_VIEWED',
  DOCUMENT_DELETED = 'DOCUMENT_DELETED',
  DOCUMENT_VERSION_ADDED = 'DOCUMENT_VERSION_ADDED',
  // AI
  AI_QUERY = 'AI_QUERY',
  AI_ANSWER_GENERATED = 'AI_ANSWER_GENERATED',
  AI_NO_SOURCE = 'AI_NO_SOURCE',
  // Dose Calculator
  DOSE_CALCULATED = 'DOSE_CALCULATED',
  DOSE_FORMULA_CREATED = 'DOSE_FORMULA_CREATED',
  DOSE_FORMULA_UPDATED = 'DOSE_FORMULA_UPDATED',
}
